### ISSUE TITLE
Consider using getopt or gflags for command line flag parsing

### ISSUE THREAD

**Issue by davidzchen** [gersteinlab/MUSIC#2]
First of all, very interesting project!

I noticed that there is a lot of boilerplate code used for parsing command line arguments. I think that this can be greatly simplified by using a command line argument parsing library, such as [getopt](http://www.gnu.org/software/libc/manual/html_node/Getopt.html) or [Google's gflags](https://code.google.com/p/gflags/?redir=1).

**Comment by ozgunharmanci** [comment]
Hey, thanks much. These are great suggestions but we defer from using external libraries like google to minimize dependencies and also to have compatibility with other projects. I will think about using getopt.
