### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by lopatica** [gersteinlab/MUSIC#3]
Hello,

I am very interested in trying out MUSIC with our MNase-seq datasets. However I return an error when installing the package. Any suggestions you might have regarding how this could be resolved would be greatly appreciated. 

Thank you

[ba0287@mtx3 MUSIC-master]$ make clean
rm -f src/main.o src/ms_peak_calling_utils.o src/ms_mapped_read_tools.o src/ms_nomenclature.o src/ms_gsl_fft_filter_utils.o src/ms_annot_region_tools.o src/ms_signal_track_tools.o src/ms_signal_enrichment_utils.o src/ms_genome_sequence_tools.o src/ms_profile_normalization.o src/ms_combinatorics.o src/ms_nucleotide.o src/ms_min_max_utils.o src/ms_xlog_math.o src/ms_utils.o src/ms_ansi_cli.o src/ms_ansi_string.o src/wavfile.o  bin/MUSIC
[ba0287@mtx3 MUSIC-master]$ make
Compiling src/main.o
In file included from /usr/include/stdio.h:929:0,
                 from src/main.cpp:1:
/usr/include/bits/stdio.h: In function '__ssize_t getline(char*_, size_t_, FILE_)':
/usr/include/bits/stdio.h:118:52: error: '__getdelim' was not declared in this scope
   return __getdelim (__lineptr, __n, '\n', __stream);
                                                    ^
makefile:10: recipe for target 'src/main.o' failed
make: *_\* [src/main.o] Error 1

**Comment by ozgunharmanci** [comment]
This issue is resolved.

**Comment by orangeSi** [comment]
hi, can you tell me how to solve this problem finally?

**Comment by orangeSi** [comment]
hi, can you tell me how to solve this problem finally?

**Comment by ozgunharmanci** [comment]
Hi, I apologize that you are having issues building music. Could you let me know exact error you are getting? 

Also, I am not seeing any compilation problems on the unix based operating systems i tried so far, including macs and on windows 7 and up. Could you let me know the operating system that you are building music on?

**Comment by orangeSi** [comment]
my computer system is centos，the error is just the same like lopatica ：
$ make
Compiling src/main.o
In file included from /usr/include/stdio.h:929:0,
from src/main.cpp:1:
/usr/include/bits/stdio.h: In function 'ssize_t getline(char*, size_t, FILE)':
/usr/include/bits/stdio.h:118:52: error: '__getdelim' was not declared in this scope
return __getdelim (__lineptr, __n, '\n', __stream);
^
makefile:10: recipe for target 'src/main.o' failed
make: ** [src/main.o] Error 1

Thanks~

**Comment by ozgunharmanci** [comment]
This is a weird problem because the error stems from code that is not in music. From what i can find online, this could be a problem with gcc installation. 

I tested building music on centos 7 and it built find.

Is there any way you could reinstall gcc and try again? Can you tell me the gcc/g++ version you are using?

**Comment by orangeSi** [comment]
I use gcc-4.9.0..

**Comment by ozgunharmanci** [comment]
Sorry for late response, I just installed gcc-4.9.2 on centos 7 and retried and it built fine. Is it possible for you to re-install gcc and try again?

**Comment by orangeSi** [comment]
my centos is not 7 , is 6.6 ...

**Comment by ozgunharmanci** [comment]
Hi, I just tested with centos 6.6, gcc-4.9.0 and it built and run with no issues. I am not sure if there is any way for me to reproduce this error. Could you do a re-install of gcc and see if that helps?

**Comment by orangeSi** [comment]
thanks~ I will try it

**Comment by ozgunharmanci** [comment]
I will keep this issue open until you have any updates.
