### ISSUE TITLE
Bug in generate multimappability script

### ISSUE THREAD

**Issue by Mashin6** [gersteinlab/MUSIC#8]
There seems to be a bug in the portion of the 'generate_multimappability_signal.csh' script that generates 'temp_map_reads.csh' file. The path to bowtie2 index is concatenated with output directory path and the 'temp_map_reads.csh' scripts fails to run. It's fixable with sed but it gives one step extra.

Initializing mappability script:
```~/software/music/bin/generate_multimappability_signal.csh \
~/software/genomes/bowtie2/fasta/dm6.fa \
76 \
~/software/genomes/bowtie2/dm6 
```

Content of generated temp_map_reads.csh
```
MUSIC -fragment_sequence_2_stdout /home/Music-test/mappability/dm6_76bp/temp/2L.bin 76 read | bowtie2 -x /home/Music-test/mappability/dm6_76bp//home/software/genomes/bowtie2/dm6 -k 5 -p 4 -f -S /dev/stdout -U /dev/stdin | MUSIC -preprocess SAM stdin /
home/Music-test/mappability/dm6_76bp/temp/2L
MUSIC -fragment_sequence_2_stdout /home/Music-test/mappability/dm6_76bp/temp/2R.bin 76 read | bowtie2 -x /home/Music-test/mappability/dm6_76bp//home/software/genomes/bowtie2/dm6 -k 5 -p 4 -f -S /dev/stdout -U /dev/stdin | MUSIC -preprocess SAM stdin /
home/Music-test/mappability/dm6_76bp/temp/2R
...
...
```

**Comment by ozgunharmanci** [comment]
I apologize sincerely for late response. Thanks much for letting know. I will fix this in the next release. 

Arif.
